### ISSUE TITLE
Handle error when offline

### ISSUE THREAD

**Issue by pratishshr** [leapfrogtechnology/reactjs-starter#11]
## Requirements
- Show a proper message to the user when he/she is offline.
- Once a request is made, check if it's a Network Connection issue and show the message as
"Please check your internet connection" in the toast.

**Comment by Krishuthapa** [comment]
I would like to work on this issue.

**Comment by Krishuthapa** [comment]
would like to work on this issue.

**Comment by pratishshr** [comment]
> would like to work on this issue.
👍
