### ISSUE TITLE
Integrate sentry for error reporting

### ISSUE THREAD

**Issue by pratishshr** [leapfrogtechnology/reactjs-starter#14]
## Requirements 
- Add a utility for instantiating `Sentry`
- An `env` var should be provided adding Sentry Token
- Sentry should only work in `Production` mode and not in other environments
- Instantiate Sentry at the start of the application.
- Add a global `componentDidCatch` lifecycle in `App.js` to catch global errors and send them to sentry

**Comment by NadeemShakya** [comment]
Can i work on this issue?

**Comment by pratishshr** [comment]
@NadeemShakya Sure. Added you as a collaborator. I'll update the description on this.
