### ISSUE TITLE
Fix precommit hook to lint and run prettier

### ISSUE THREAD

**Issue by pratishshr** [leapfrogtechnology/reactjs-starter#16]
## Requirements
- Currently pre commit hook does not seem to be executing

**Comment by Krishuthapa** [comment]
I would like to work on this bug

**Comment by pratishshr** [comment]
@Krishuthapa Sure. Added you to the repo.

**Comment by Krishuthapa** [comment]
In which file isn't it working? I checked it for js and json and its working fine for them

**Comment by pratishshr** [comment]
Looks like it's only in my laptop 🤷‍♂️ . Seems to be working fine for others.
Closing this.

@Krishuthapa You can take over other Issues if you like.

**Comment by Krishuthapa** [comment]
ok
