### ISSUE TITLE
Add search filter to react table

### ISSUE THREAD

**Issue by anishmanandhar** [leapfrogtechnology/reactjs-starter#19]
**REQUIREMENTS**

- Add a search text field above the react table and search employee by the first name.
- The search should result from the API call.
- Search after user enters 3 characters
- Search on ENTER key press.
- Add debounce and throttling capabilities.

Check this JSON server mock API for reference 
https://www.npmjs.com/package/json-server#filter

<img width="406" alt="Screen Shot 2020-05-01 at 10 54 50 AM" src="https://user-images.githubusercontent.com/5500400/80783676-3a721180-8b9a-11ea-8930-3cbe74af8a90.png">

**Comment by sumansta** [comment]
Can I take this? @pratishshr

**Comment by pratishshr** [comment]
sure @sumansta . Added you to the repo.
@anishmanandhar Could you explain what kind of filter are we looking for in this issue?

**Comment by anishmanandhar** [comment]
@sumansta updated the description. please check it.

**Comment by sumansta** [comment]
@anishmanandhar 
Should the search API be triggered on `inputChange` or only when `FilterList` is clicked?
Also, as there are `firstName` and `lastName`  in `db.json`, do I need to handle the search by either of the name or a full name?

**Comment by anishmanandhar** [comment]
@sumansta lets search on input change, Add debounce capability also.
Look at this article for reference
https://levelup.gitconnected.com/debounce-in-javascript-improve-your-applications-performance-5b01855e086
