### ISSUE TITLE
[CRUD] Integrate a flow for "Create"

### ISSUE THREAD

**Issue by pratishshr** [leapfrogtechnology/reactjs-starter#6]
## Requirements
- Add a flow to `Add` a resource
- Form Handling (Use latest version of Formik)
- Validation (Should have Yup Validation)
- Create a new route for the form
- There's already an `EmployeeForm` component. Take a look at that and integrate it into the application.

**Comment by chawocecil** [comment]
Can I take this?

**Comment by pratishshr** [comment]
Sure @chawocecil . I'll add you to the repo. Will update the description as well.
